# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab4a2b4f590ed7c82fac639691b9db3c80622827de35e99ef0e5467577ab1cfceb9a07f82ebb91863ef83d15ded3b53573208a45f8ee26b36c8f4fd08f4906bd

test:
  secret_key_base: 8836b9acf9ba20a6dc895d3ad308958184457b6463c2643fd0a2b7742c6b31757efff387c46712dc59a5ea36435805ff2150bac76bfb7b9a372c067a08febaa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
